### ISSUE TITLE
Really struggling getting css images to work with this theme

### ISSUE THREAD

**Issue by pastorryanhayden** [austenc/freebird#2]
I hate to bug you but I cannot for the life of me figure out how relative images are supposed to work in the css.  In my css file in resources I have this:

```css
.dark_pattern {
	background: url('../img/worn_dots.png') repeat;
}
```
Which is compiling to to this in the /css/theme.css file:

```css
.dark_pattern {
  background: url(/images/worn_dots.png?6f9f26572c7b2bf00a8171a41ab080f0) repeat;
}
```
But that folder doesn't exist and it isn't showing up on the front end.  Any help would be huge.  Thanks for the theme setup.
